version: "3.8"

services:
  blog:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - blog-data:/app/data
    environment:
      - PORT=8080
      - BLOG_DATA_DIR=/app/data

volumes:
  blog-data:
