[phases.setup]
nixPkgs = ["nodejs_22", "go_1_21", "npm-9_x"]

[phases.install]
cmds = ["npm install", "cd frontend && npm install", "cd ../backend && go mod download"]

[phases.build]
cmds = ["npm run build:frontend", "cd backend && go build -o ../dist/backend main.go"]

[start]
cmd = "cd dist && ./backend"
