// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/blogs/new": {
    params: {};
  };
  "/blogs/:slug/edit": {
    params: {
      "slug": string;
    };
  };
  "/blogs/:slug": {
    params: {
      "slug": string;
    };
  };
  "/sitemap.xml": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/blogs/new" | "/blogs/:slug/edit" | "/blogs/:slug" | "/sitemap.xml" | "/*";
  };
  "routes/index.tsx": {
    id: "routes/index";
    page: "/";
  };
  "routes/blogs/new.tsx": {
    id: "routes/blogs/new";
    page: "/blogs/new";
  };
  "routes/blogs/$slug.edit.tsx": {
    id: "routes/blogs/$slug.edit";
    page: "/blogs/:slug/edit";
  };
  "routes/blogs/$slug.tsx": {
    id: "routes/blogs/$slug";
    page: "/blogs/:slug";
  };
  "routes/sitemap.xml.tsx": {
    id: "routes/sitemap.xml";
    page: "/sitemap.xml";
  };
  "routes/404.tsx": {
    id: "routes/404";
    page: "/*";
  };
};